services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=mysql
      - FORGEJO__database__HOST=mariadb
      - FORGEJO__database__NAME=${MARIADB_DATABASE}
      - FORGEJO__database__USER=${MARIADB_USER}
      - FORGEJO__database__PASSWD=${MARIADB_PASSWORD}
    volumes:
      - forgejo:/data
    networks:
      - external
      - internal
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: forgejo-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  forgejo:
  mariadb:

networks:
  external:
  internal:
