services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - home-assistant_external
      - nextcloud_external
      - forgejo_external

networks:
  home-assistant_external:
    external: true
  nextcloud_external:
    external: true
  forgejo_external:
    external: true
